### ISSUE TITLE
Cannot find module 'ascallback'

### ISSUE THREAD

**Issue by viniciussbs** [brikteknologier/seraph#202]
Hi,

There's a bug on version 0.15.0:

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'ascallback'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/node_modules/seraph/lib/bolt/seraph.js:5:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

Adding `'ascallback'` in package.json should solve.

**Comment by jonpacker** [comment]
crap! thanks!

**Comment by jonpacker** [comment]
yeah, that commit message should read "_add_ missing ascallback dependency". my bad.
