### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by schabluk** [brikteknologier/seraph#204]
I have this error in my Meteor app when using seraph version 0.15.2.

`import seraph from 'seraph';`

Version 0.14.3 works fine. 

20160813-17:09:24.681(2)? (STDERR) /Users/lusch/projects/Telescope/.meteor/local/build/programs/server/packages/modules.js:195300
W20160813-17:09:24.682(2)? (STDERR)   let p = promise.then(function (ret) {
W20160813-17:09:24.682(2)? (STDERR)   ^^^     
W20160813-17:09:24.682(2)? (STDERR)           
W20160813-17:09:24.683(2)? (STDERR) SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
W20160813-17:09:24.683(2)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20160813-17:09:24.683(2)? (STDERR)     at /Users/lusch/projects/Telescope/.meteor/local/build/programs/server/boot.js:292:30
W20160813-17:09:24.683(2)? (STDERR)     at Array.forEach (native)
W20160813-17:09:24.683(2)? (STDERR)     at Function._.each._.forEach (/Users/lusch/.meteor/packages/meteor-tool/.1.4.0.1podkn9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160813-17:09:24.684(2)? (STDERR)     at /Users/lusch/projects/Telescope/.meteor/local/build/programs/server/boot.js:133:5

**Comment by parties** [comment]
Does this work for you?

```
import * as seraph from "seraph";
```
